### ISSUE TITLE
Investigate using prettier for formatting consistence

### ISSUE THREAD

**Issue by donovanmuller** [absa-subatomic/photon#9]
We should investigate using [prettier](https://github.com/prettier/prettier) for easier ode formatting.

See https://www.youtube.com/watch?v=YIvjKId9m2c for reference.

**Comment by akserg** [comment]
Referenced to [Formatting Code Automatically](https://github.com/absa-subatomic/photon/wiki/Formatting-Code-Automatically) on Wiki.

**Comment by akserg** [comment]
Zubair added the Prettier in [b375cb6177c278033e258e338ba51d299bcf415f](https://github.com/absa-subatomic/photon/commit/b375cb6177c278033e258e338ba51d299bcf415f)
